import { cn } from '@/lib/utils'

/**
 * The Perfect Vision brand asset. One file, used everywhere.
 *
 * There is deliberately NO icon-library fallback and NO simplified variant.
 * Earlier revisions had both, and the result was an eye-only mark appearing
 * in the sidebar and mobile bar while the full logo showed on entry screens —
 * two different logos in one product. If the asset ever fails to load, the
 * wordmark stands alone rather than substituting a different mark.
 *
 * ─────────────────────────────────────────────────────────────────────────
 *  TO REPLACE THE LOGO: overwrite these two files and rebuild. No code edits.
 *
 *    public/logo.svg      the brand asset used throughout the interface
 *    public/logo.png      raster fallback, generated by `npm run logo:png`
 *
 *  public/favicon.svg is a copy of logo.svg — keep them identical so the
 *  browser tab, installed app icon and in-app logo never diverge.
 * ─────────────────────────────────────────────────────────────────────────
 */

type Tone = 'onLight' | 'onDark'

// BASE_URL is rewritten per deployment, so this resolves whether the app is
// served from the root or from /billing_project/ on GitHub Pages.
const LOGO_SRC = `${import.meta.env.BASE_URL}logo.svg`

/**
 * The brand asset on its own, no wordmark.
 *
 * The image is object-contain inside whatever box the caller sizes, so the
 * artwork keeps its own aspect ratio and is never stretched.
 */
export function LogoMark({ className }: { className?: string; tone?: Tone }) {
  return (
    <img
      src={LOGO_SRC}
      alt="Perfect Vision Billing Software"
      className={cn('h-full w-full shrink-0 object-contain', className)}
    />
  )
}

/**
 * Brand asset plus wordmark, in the hierarchy:
 *   Perfect Vision   (primary)
 *   BILLING SOFTWARE (secondary)
 *   Smart billing. Clear vision. (tagline, entry screens only)
 */
export function Logo({
  className,
  tone = 'onLight',
  size = 'md',
  showTagline = false,
  stacked = false,
  /** Wordmark off when the surrounding layout already names the product. */
  showWordmark = true,
}: {
  className?: string
  tone?: Tone
  size?: 'sm' | 'md' | 'lg' | 'xl'
  showTagline?: boolean
  stacked?: boolean
  showWordmark?: boolean
}) {
  const box = {
    sm: 'h-9 w-9',
    md: 'h-11 w-11',
    lg: 'h-14 w-14',
    xl: 'h-20 w-20 sm:h-24 sm:w-24',
  }[size]

  const primaryText = {
    sm: 'text-sm',
    md: 'text-base',
    lg: 'text-lg',
    xl: 'text-2xl sm:text-3xl',
  }[size]

  const secondaryText = size === 'xl' ? 'text-[11px] sm:text-xs' : size === 'sm' ? 'text-[10px]' : 'text-xs'

  const primaryColor = tone === 'onDark' ? 'text-cream-50' : 'text-brand-900'
  const secondaryColor = tone === 'onDark' ? 'text-brand-300' : 'text-brand-600'

  // No tinted container: the artwork carries its own shape, and a box behind
  // it would read as a second, competing mark.
  const mark = (
    <span className={cn('flex shrink-0 items-center justify-center', box)}>
      <LogoMark />
    </span>
  )

  const words = showWordmark ? (
    <span className={cn('leading-tight', stacked && 'text-center')}>
      <span className={cn('block font-semibold tracking-tight', primaryText, primaryColor)}>
        Perfect Vision
      </span>
      <span
        className={cn(
          'block font-semibold tracking-[0.18em] uppercase',
          secondaryText,
          secondaryColor,
        )}
      >
        Billing Software
      </span>
      {showTagline && (
        <span
          className={cn(
            'mt-1.5 block text-[10px] font-semibold tracking-[0.12em] uppercase',
            tone === 'onDark' ? 'text-brand-400' : 'text-brand-500',
          )}
        >
          Smart billing. Clear vision.
        </span>
      )}
    </span>
  ) : null

  return stacked ? (
    <div className={cn('flex flex-col items-center gap-3', className)}>
      {mark}
      {words}
    </div>
  ) : (
    <div className={cn('flex items-center gap-2.5', className)}>
      {mark}
      {words}
    </div>
  )
}
